### ISSUE TITLE
Seg fault after running

### ISSUE THREAD

**Issue by salotz** [thomasdeniau/pyfauxfur#2]
I get a seg fault after I either step or run after gui launches. Run generates an image and then crashes, step I get nothing. Tested on Ubuntu 14.04 in python-2.7. Cool idea!

**Comment by thomasdeniau** [comment]
Sorry, this is a project from when I was still a student 10 years ago. I don't have much time to update it :-)

**Comment by salotz** [comment]
I understand completely. Just wanted to put it out there.
